---
title: "eds-212-day-2"
author: "Connor Flynn"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library('tidyverse')
library('palmerpenguins')



```



```{r}
# Find the derivative expression

fx <- expression(x^2)
x <- 3
df_dx <- D(expr = fx, name = 'x')
df_dx
eval(expr = df_dx)



px <- expression(2 *(3*a+2)^4 * (4−5))
a <- 1.2
df_da <- D(expr = px, name = 'a')
df_da

eval(expr =df_da)
```


```{r}
### Second Derivative

gx <- expression(4.6 - (1.9 * z ^ 3))
dg_dx <- D(expr = gx, name = 'z')
dg_dx


g2x <- expression(dg_dx)
dg2_dx2 <- D(expr = g2x, name = 'z')
dg2_dx2
```


```{r}
# Find all Partials 

f_xyz <- expression((2*x^2*y)-(3*x+1+4*z^4*x))
df_dx <- D(expr = f_xyz, 'x')
df_dx

df_dy <- D(expr = f_xyz, 'y')
df_dy

df_dz <- D(expr = f_xyz, 'z')
df_dz
```




```{r}
# Make Some Plots
f_x <- function(x) {
  2.4 * exp(-0.005) * x * sin(x)
}
ggplot(data = data.frame(x = c(-0.5, 0.5)), aes(x = x)) +
  stat_function(fun = f_x)




```




```{r}
#Penguins

ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species))






```

